# Generated by Django 4.1.3 on 2022-12-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dummy_as_text',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='total_points_as_text',
            field=models.TextField(default='[]'),
        ),
    ]
